# Flags
OUTPUT_AREA = ../../output_location_ignore
COMPILE_FLAGS = -std=gnu99 -ffreestanding -O2 -Wall -Wextra
COMPILER_DIR = ../../compilers/bin/i686-elf-gcc


compile:
	$(COMPILER_DIR) -c shell/temp_shell.c -o $(OUTPUT_AREA)/temp_shell.o $(COMPILE_FLAGS)